version: '2'
services:
  webserver:
    image: phpstorm/php-56-apache-xdebug-25
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host:172.21.0.1 remote_port=9001