version: '2'
services:
  webserver:
    image: webdevops/php-apache-dev:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_REMOTE_HOST: 172.17.0.1
      XDEBUG_REMOTE_PORT: 9001



